events {
    worker_connections 1024;
}
http {
    resolver 127.0.0.11 valid=5s;
    server {
        listen 4444;
        location / {
            set $backend_ui "http://selenoid-ui:8080";
            proxy_pass $backend_ui;
            proxy_buffering off;
        }
        location ~ /(vnc|logs)/ {
            set $backend_ui "http://selenoid-ui:8080";
            proxy_pass $backend_ui;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
        location /wd/hub/ {
            set $backend_ggr "http://ggr:4444";
            proxy_pass $backend_ggr;
        }
    }
}
