[pytest]
pythonpath = .
addopts = -v -s
markers =
    homework_03: Test of all figures (circle, rectangle, square, triangle)
    homework_05_all: API tests (Dog API, JSONPlaceholder, OpenBreweryDB)
    homework_05_options: CLI options tests (--url, --status_code)
